version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myapp

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop.sh
      runas: ubuntu
