version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
permissions:
  - object: /var/www/html
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
  - object: /var/www/html
    owner: ubuntu
    group: ubuntu  
    mode: 644
    type:
      - file
