version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Starting pre_build phase..."
      - python3 --version

  build:
    commands:
      - echo "Build phase started on `date`"

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
